language: java
jdk:
- openjdk11
deploy:
  provider: releases
  api_key:
    secure: p/NTLYKS7gc16Ie931k2BzADJ79U7Hgj8LELlysdQIPKKwxHk+f613nyJD2pa1EAK9cxeGjdyKOBWFPfNTjB9Ufz61I74TZHcVxs2pp8zQ3Hh1XeUMht5zraNExKrN5ZfXqZcwFHDSaauu1sersOz7ec1SYgwmM9fZVQaIOZyL3y3WD/Bex+8VT9kogBeA5pYrNyohnSUF2kovi/zxa948DnzTC0dSm5f7t1ixMj+A3rFvbn2xM43Ozm5sfYCJp8XmWyx0dvjaHSt/rBSFeEohtlP+948Pjd1dcIqbtQSJyDB6Hae/fo9mS4+xPM3sDf1ZUm3Pk/Ry7Ji4u1H8oogiWoR5wMsxGQl6E0OKvFN0hAYghHxqrckidwYeLkqgJeWtZQXujRtt9HfmF+Za685lypFd0E75pmAaXYetZ2ogHgOuG24HrxJbfSS1kQwj5xJNlOBMZxT+4LbopEzmkDew8y7SehLFEJ+NofUSxAn+DZoCGpqyyF3gJBAhudktJaGb5nnkMt6FojdelT7Fp64JhPkrCgkK/M9yp1UZEPB8Q2lHmL9zjT0nooiGin6/7TP76z9LS8y8JqsNRhdiykgRJHykEDf3sEChpO2YtPH/rz2mwQ+w9egxZqJCtNANS/LeL7yQ6RRetDMkFr2gPR0dio05m8T1JAZAo/w2czA10=
  file_glob: true
  file: "target/chess-endgames-release-*.jar"
  skip_cleanup: true
  on:
    tags: true
